# Generated by Django 6.0.6 on 2026-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(default='One Way', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
