# Generated by Django 6.0.6 on 2026-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_passengers_booking_route_booking_trip_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('pickup', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('trip_type', models.CharField(default='One Way', max_length=50)),
                ('passengers', models.IntegerField(default=1)),
                ('route', models.CharField(default='N/A', max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
