# Generated by Django 6.0.6 on 2026-09-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_indexbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbooking',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
